name: Publish Python Package (Poetry)

on:
  push:
    branches:
      - main # Publish on push to the main branch
  release:
    types: [created] # Publish on new GitHub release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Adjust Python version as needed

      # Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Regenerate lock file if necessary
      - name: Ensure lockfile is up to date
        run: |
          if ! poetry lock --check; then
            poetry lock --no-update
          fi

      # Install dependencies
      - name: Install dependencies
        run: poetry install

      # Build the package
      - name: Build the package
        run: poetry build

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }} # PyPI token stored in GitHub secrets
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
